<a href="https://colab.research.google.com/github/ds-raw/MLClass/blob/main/UAS%20Machine%20Learning/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing PyTorch

In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

## Introduction to tensors

Sekarang kita telah mengimpor PyTorch, saatnya mempelajari tentang tensor.

Tensor adalah elemen dasar pembelajaran mesin.

Tugas mereka adalah merepresentasikan data secara numerik.

Misalnya, Anda dapat merepresentasikan gambar sebagai tensor dengan bentuk [3, 224, 224] yang artinya [saluran_warna, tinggi, lebar], karena pada gambar memiliki 3 saluran warna (merah, hijau, biru), tingginya 224 piksel dan lebar 224 piksel..

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

Dalam bahasa tensor (bahasa yang digunakan untuk mendeskripsikan tensor), tensor akan memiliki tiga dimensi, satu untuk `saluran_warna`, `tinggi`, dan `lebar`.

Tapi kita lebih maju dari diri kita sendiri.

Mari pelajari lebih lanjut tentang tensor dengan mengkodekannya.

### Creating tensors

PyTorch menyukai tensor. Sedemikian rupa sehingga ada seluruh halaman dokumentasi yang didedikasikan untuk kelas [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html).

Pekerjaan rumah pertama Anda adalah [membaca dokumentasi di `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) selama 10 menit. Tapi Anda bisa membahasnya nanti.

Mari membuat kode.

Hal pertama yang akan kita buat adalah **skalar**.

Skalar adalah bilangan tunggal dan dalam istilah tensor merupakan tensor berdimensi nol.

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

Lihat bagaimana `tensor(7)` di atas dicetak?

Artinya, meskipun `skalar` adalah angka tunggal, ia bertipe `torch.Tensor`.

Kita dapat memeriksa dimensi tensor menggunakan atribut `ndim`.

In [ ]:
scalar.ndim

0

Bagaimana jika kita ingin mengambil nomor dari tensor?

Misalnya, ubah dari `torch.Tensor` menjadi bilangan bulat Python?

Untuk melakukannya kita dapat menggunakan metode `item()`.


To do we can use the `item()` method.

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

Oke, sekarang mari kita lihat **vektor**.

Vektor adalah tensor berdimensi tunggal tetapi dapat memuat banyak bilangan.

Misalnya, Anda dapat memiliki vektor `[3, 2]` untuk mendeskripsikan `[kamar tidur, kamar mandi]` di rumah Anda. Atau Anda dapat menggunakan `[3, 2, 2]` untuk mendeskripsikan `[kamar tidur, kamar mandi, tempat parkir mobil]` di rumah Anda.

Tren penting di sini adalah bahwa suatu vektor fleksibel dalam hal apa yang dapat diwakilinya (sama dengan tensor).

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

Hebatnya, `vektor` sekarang berisi dua angka 7, angka favorit saya.

Menurut Anda, berapa banyak dimensi yang dimilikinya?

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

Hmm aneh, `vektor` berisi dua angka tetapi hanya memiliki satu dimensi.

Saya akan memberi tahu Anda sebuah trik.

Anda dapat mengetahui jumlah dimensi yang dimiliki tensor di PyTorch dengan jumlah tanda kurung siku di bagian luarnya (`[`) dan Anda hanya perlu menghitung satu sisinya.

Berapa banyak tanda kurung siku yang dimiliki `vektor`?

Konsep penting lainnya untuk tensor adalah atribut `bentuknya`. Bentuknya memberi tahu Anda bagaimana elemen-elemen di dalamnya disusun.

Mari kita periksa bentuk `vektor`.

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

Di atas mengembalikan `torch.Size([2])` yang berarti vektor kita berbentuk `[2]`. Ini karena dua elemen yang kita tempatkan di dalam tanda kurung siku (`[7, 7]`).

Sekarang mari kita lihat **matriks**.

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

Wow! Lebih banyak angka! Matriks sama fleksibelnya dengan vektor, hanya saja matriks tersebut mempunyai dimensi ekstra.

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

`MATRIX` mempunyai dua dimensi (apakah Anda menghitung jumlah tanda kurung siku di luar salah satu sisinya?).

Menurut Anda `bentuk` apa yang akan dimilikinya?

In [ ]:
MATRIX.shape

torch.Size([2, 2])

Kita mendapatkan keluaran `torch.Size([2, 2])` karena `MATRIX` memiliki kedalaman dua elemen dan lebar dua elemen.

Bagaimana kalau kita membuat **tensor**?

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

Wow! Tensor yang terlihat bagus.

Saya ingin menekankan bahwa tensor dapat mewakili hampir semua hal.

Yang baru saja kita buat bisa jadi adalah angka penjualan toko steak dan mentega almond (dua makanan favorit saya).

![tensor sederhana di lembar Google yang menampilkan hari dalam seminggu, penjualan steak, dan penjualan mentega almond](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_simple_tensor.png)

Menurut Anda, berapa banyak dimensi yang dimilikinya? (petunjuk: gunakan trik menghitung tanda kurung siku)

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

Lalu bagaimana dengan bentuknya?

In [ ]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

Baiklah, ini menghasilkan `torch.Size([1, 3, 3])`.

Dimensinya dari luar ke dalam.

Artinya ada 1 dimensi 3 kali 3.

![contoh dimensi tensor yang berbeda](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Catatan:** Anda mungkin memperhatikan saya menggunakan huruf kecil untuk `skalar` dan `vektor` serta huruf besar untuk `MATRIX` dan `TENSOR`. Ini memang disengaja. Dalam praktiknya, Anda akan sering melihat skalar dan vektor dilambangkan dengan huruf kecil seperti `y` atau `a`. Dan matriks dan tensor dilambangkan dengan huruf besar seperti `X` atau `W`.
>
> Anda juga mungkin memperhatikan nama martrix dan tensor digunakan secara bergantian. Ini biasa terjadi. Karena di PyTorch Anda sering berurusan dengan `torch.Tensor`s (karena itulah nama tensornya), namun bentuk dan dimensi isi akan menentukan isi sebenarnya.

Mari kita rangkum.

| Nama | Apa itu? | Jumlah dimensi | Bawah atau atas (biasanya/contoh) |
| ----- | ----- | ----- | ----- |
| **skalar** | satu nomor | 0 | Lebih rendah (`a`) |
| **vektor** | angka dengan arah (misalnya kecepatan angin dengan arah) tetapi bisa juga memiliki banyak angka lainnya | 1 | Bawah (`y`) |
| **matriks** | array angka 2 dimensi | 2 | Atas (`Q`) |
| **tensor** | array bilangan berdimensi n | bisa berupa bilangan apa pun, tensor 0 dimensi adalah skalar, tensor 1 dimensi adalah vektor | Atas (`X`) |

![tensor matriks vektor skalar dan tampilannya](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### Random tensors

Kami telah menetapkan tensor yang mewakili beberapa bentuk data.

Dan model pembelajaran mesin seperti jaringan saraf memanipulasi dan mencari pola dalam tensor.

Namun saat membuat model pembelajaran mesin dengan PyTorch, jarang sekali Anda membuat tensor dengan tangan (seperti yang sedang kami lakukan).

Sebaliknya, model pembelajaran mesin sering kali dimulai dengan tensor angka acak yang besar dan menyesuaikan angka acak tersebut saat model tersebut bekerja melalui data untuk merepresentasikannya dengan lebih baik.

Intinya:

`Mulai dengan angka acak -> lihat data -> perbarui nomor acak -> lihat data -> perbarui nomor acak...`

Sebagai data scientist, Anda dapat menentukan cara model pembelajaran mesin dimulai (inisialisasi), melihat data (representasi), dan memperbarui (optimasi) angka acaknya.

Kami akan langsung melakukan langkah-langkah ini nanti.

Untuk saat ini, mari kita lihat cara membuat tensor bilangan acak.

Kita dapat melakukannya menggunakan [`torch.rand()`](https://pytorch.org/docs/stable/generated/torch.rand.html) dan meneruskan parameter `size`.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.8922, 0.4360, 0.3222, 0.1369],
         [0.7514, 0.5605, 0.2706, 0.7167],
         [0.6146, 0.5510, 0.7605, 0.6603]]),
 torch.float32)

Fleksibilitas dari `torch.rand()` adalah kita dapat mengatur `ukuran` menjadi apapun yang kita inginkan.

Misalnya, Anda menginginkan tensor acak dalam bentuk gambar umum `[224, 224, 3]` (`[tinggi, lebar, saluran_warna`]).


In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

Terkadang Anda hanya ingin mengisi tensor dengan nol atau satu.

Hal ini sering terjadi dengan masking (seperti menutupi beberapa nilai dalam satu tensor dengan nol agar model tahu untuk tidak mempelajarinya).

Mari kita buat tensor yang penuh dengan angka nol dengan [`torch.zeros()`](https://pytorch.org/docs/stable/generated/torch.zeros.html)

Sekali lagi, parameter `ukuran` ikut berperan.

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

Kita dapat melakukan hal yang sama untuk membuat tensor semuanya kecuali menggunakan [`torch.ones()` ](https://pytorch.org/docs/stable/generated/torch.ones.html) sebagai gantinya.

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

Terkadang Anda mungkin menginginkan rentang angka, seperti 1 hingga 10 atau 0 hingga 100.

Anda dapat menggunakan `torch.arange(start, end, step)` untuk melakukannya.

Di mana:
* `start` = awal rentang (misalnya 0)
* `end` = akhir rentang (misalnya 10)
* `langkah` = berapa banyak langkah di antara setiap nilai (misalnya 1)

> **Catatan:** Dengan Python, Anda dapat menggunakan `range()` untuk membuat rentang. Namun di PyTorch, `torch.range()` tidak digunakan lagi dan mungkin menampilkan kesalahan di masa mendatang.

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-18-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Terkadang Anda mungkin menginginkan satu tensor jenis tertentu dengan bentuk yang sama dengan tensor lainnya.

Misalnya tensor yang semuanya nol dengan bentuk yang sama dengan tensor sebelumnya.

Untuk melakukannya, Anda dapat menggunakan [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) atau [`torch.ones_like(input)`](https ://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) yang mengembalikan tensor yang diisi dengan nol atau satu dalam bentuk yang sama dengan `input`.

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Ada banyak [tipe data tensor yang tersedia di PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Ada yang khusus untuk CPU dan ada pula yang lebih baik untuk GPU.

Mengenal mana yang membutuhkan waktu.

Umumnya jika Anda melihat `torch.cuda` di mana pun, tensornya digunakan untuk GPU (karena GPU Nvidia menggunakan perangkat komputasi yang disebut CUDA).

Jenis yang paling umum (dan umumnya default) adalah `torch.float32` atau `torch.float`.

Ini disebut sebagai "titik mengambang 32-bit".

Namun ada juga floating point 16-bit (`torch.float16` atau `torch.half`) dan floating point 64-bit (`torch.float64` atau `torch.double`).

Dan yang lebih membingungkan lagi, ada juga bilangan bulat 8-bit, 16-bit, 32-bit, dan 64-bit.

Ditambah lagi!

> **Catatan:** Bilangan bulat adalah bilangan bulat datar seperti `7` sedangkan bilangan bulat memiliki desimal `7,0`.

Alasan semua ini berkaitan dengan **presisi dalam komputasi**.

Presisi adalah jumlah detail yang digunakan untuk mendeskripsikan suatu angka.

Semakin tinggi nilai presisinya (8, 16, 32), semakin detail pula data yang digunakan untuk menyatakan suatu bilangan.

Hal ini penting dalam pembelajaran mendalam dan komputasi numerik karena Anda melakukan begitu banyak operasi, semakin banyak detail yang harus Anda hitung, semakin banyak komputasi yang harus Anda gunakan.

Jadi tipe data dengan presisi lebih rendah umumnya lebih cepat untuk dihitung tetapi mengorbankan beberapa kinerja pada metrik evaluasi seperti akurasi (lebih cepat untuk dihitung tetapi kurang akurat).

> **Sumber Daya:**
  * Lihat [dokumentasi PyTorch untuk daftar semua tipe data tensor yang tersedia](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Baca [halaman Wikipedia untuk ikhtisar tentang presisi dalam komputasi](https://en.wikipedia.org/wiki/Precision_(computer_science)) yang dimaksud.

Mari kita lihat cara membuat beberapa tensor dengan tipe data tertentu. Kita dapat melakukannya menggunakan parameter `dtype`.

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Selain masalah bentuk (bentuk tensor tidak cocok), dua masalah paling umum lainnya yang akan Anda temui di PyTorch adalah masalah tipe data dan perangkat.

Misalnya, salah satu tensor adalah `torch.float32` dan yang lainnya adalah `torch.float16` (PyTorch sering kali menyukai tensor dengan format yang sama).

Atau salah satu tensor Anda ada di CPU dan yang lainnya ada di GPU (PyTorch menyukai penghitungan antar tensor berada di perangkat yang sama).

Kita akan melihat lebih banyak pembicaraan tentang perangkat ini nanti.

Untuk saat ini mari buat tensor dengan `dtype=torch.float16`.

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

Setelah Anda membuat tensor (atau orang lain atau modul PyTorch telah membuatnya untuk Anda), Anda mungkin ingin mendapatkan beberapa informasi dari tensor tersebut.

Kami telah melihat ini sebelumnya, tetapi tiga atribut paling umum yang ingin Anda ketahui tentang tensor adalah:
* `bentuk` - apa bentuk tensornya? (beberapa operasi memerlukan aturan bentuk tertentu)
* `dtype` - tipe data apa yang menyimpan elemen dalam tensor?
* `perangkat` - di perangkat apa tensor disimpan? (biasanya GPU atau CPU)

Mari buat tensor acak dan cari tahu detailnya.

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3989, 0.9909, 0.1129, 0.4657],
        [0.0733, 0.8086, 0.4195, 0.3318],
        [0.1768, 0.8504, 0.9022, 0.5777]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


> **Note:** When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":
  * "*what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where*"

## Manipulating tensors (tensor operations)

Dalam pembelajaran mendalam, data (gambar, teks, video, audio, struktur protein, dll) direpresentasikan sebagai tensor.

Sebuah model belajar dengan menyelidiki tensor tersebut dan melakukan serangkaian operasi (bisa memakan waktu 1.000.000 detik+) pada tensor untuk membuat representasi pola dalam data masukan.

Operasi-operasi ini seringkali merupakan tarian yang indah antara:
* Tambahan
* Pengurangan
* Perkalian (berdasarkan elemen)
* Divisi
* Perkalian matriks

Dan itu saja. Tentu masih ada beberapa lagi di sana-sini, tetapi ini adalah blok dasar jaringan saraf.

Dengan menyusun blok penyusun ini dengan cara yang benar, Anda dapat membuat jaringan saraf tercanggih (seperti lego!).

### Basic operations

Mari kita mulai dengan beberapa operasi dasar, penjumlahan (`+`), pengurangan (`-`), perkalian (`*`).

Mereka bekerja seperti yang Anda kira.

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Perhatikan bagaimana nilai tensor di atas tidak menjadi `tensor([110, 120, 130])`, hal ini karena nilai di dalam tensor tidak berubah kecuali jika ditetapkan ulang.

In [ ]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

Mari kita kurangi sebuah angka dan kali ini kita akan menetapkan ulang variabel `tensor`.

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch juga memiliki banyak fungsi bawaan seperti [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (kependekan dari perkalian) dan [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) untuk melakukan operasi dasar.

In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

Namun, lebih umum menggunakan simbol operator seperti `*` daripada `torch.mul()`

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

Salah satu operasi paling umum dalam algoritma pembelajaran mesin dan pembelajaran mendalam (seperti jaringan neural) adalah [perkalian matriks](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch mengimplementasikan fungsi perkalian matriks dalam metode [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html).

Dua aturan utama perkalian matriks yang perlu diingat adalah:

1. **Dimensi bagian dalam** harus sesuai:
  * `(3, 2) @ (3, 2)` tidak akan berfungsi
  * `(2, 3) @ (3, 2)` akan berfungsi
  * `(3, 2) @ (2, 3)` akan berfungsi
2. Matriks yang dihasilkan berbentuk **dimensi luar**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

> **Catatan:** "`@`" dengan Python adalah simbol perkalian matriks.

> **Sumber Daya:** Anda dapat melihat semua aturan perkalian matriks menggunakan `torch.matmul()` [dalam dokumentasi PyTorch](https://pytorch.org/docs/stable/generated/torch.matmul. html).

Mari kita membuat tensor dan melakukan perkalian berdasarkan elemen dan perkalian matriks di atasnya.



In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

Perbedaan antara perkalian elemen dan perkalian matriks adalah penjumlahan nilainya.

Untuk variabel `tensor` kami dengan nilai `[1, 2, 3]`:

| Operasi | Perhitungan | Kode |
| ----- | ----- | ----- |
| **Perkalian berdasarkan elemen** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Perkalian matriks** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

Anda dapat melakukan perkalian matriks dengan tangan tetapi hal ini tidak disarankan.

Metode `torch.matmul()` bawaan lebih cepat.

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.2 ms, sys: 36 µs, total: 1.23 ms
Wall time: 1.11 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 359 µs, sys: 68 µs, total: 427 µs
Wall time: 343 µs


tensor(14)

## Salah satu kesalahan paling umum dalam pembelajaran mendalam (kesalahan bentuk)

Karena sebagian besar pembelajaran mendalam adalah mengalikan dan melakukan operasi pada matriks, dan matriks memiliki aturan ketat tentang bentuk dan ukuran apa yang dapat digabungkan, salah satu kesalahan paling umum yang akan Anda temui dalam pembelajaran mendalam adalah ketidakcocokan bentuk.

In [ ]:


torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
result = torch.matmul(tensor_A, tensor_B.T)

Kita dapat membuat perkalian matriks berfungsi antara `tensor_A` dan `tensor_B` dengan mencocokkan dimensi dalamnya.

Salah satu cara untuk melakukannya adalah dengan **transpose** (mengganti dimensi tensor tertentu).

Anda dapat melakukan transpos di PyTorch menggunakan:
* `torch.transpose(input, dim0, dim1)` - dengan `input` adalah tensor yang diinginkan untuk diubah posisinya dan `dim0` dan `dim1` adalah dimensi yang akan ditukar.
* `tensor.T` - dengan `tensor` adalah tensor yang diinginkan untuk diubah posisinya.

Mari kita coba yang terakhir.

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Anda juga dapat menggunakan [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html) yang merupakan kependekan dari `torch.matmul()`.

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Tanpa transpos, aturan perkalian matriks tidak terpenuhi dan kita mendapatkan error seperti di atas.

Bagaimana dengan visualnya?

![demo visual perkalian matriks](https://github.com/mrdbourke/pytorch-deep-learning/raw/main/images/00-matrix-multiply-crop.gif)

Anda dapat membuat visual perkalian matriks sendiri seperti ini di http://matrixmultiplication.xyz/.

> **Catatan:** Perkalian matriks seperti ini disebut juga sebagai [**perkalian titik**](https://www.mathsisfun.com/algebra/vectors-dot-product.html) dari dua matriks .

Jaringan saraf penuh dengan perkalian matriks dan perkalian titik.

Modul [`torch.nn.Linear()`](https://pytorch.org/docs/1.9.1/generated/torch.nn.Linear.html) (kita akan melihatnya beraksi nanti), juga dikenal sebagai lapisan feed-forward atau lapisan yang terhubung sepenuhnya, mengimplementasikan perkalian matriks antara masukan `x` dan matriks bobot `A`.

$$
y = x\cdot{A^T} + b
$$

Di mana:
* `x` adalah masukan ke lapisan (pembelajaran mendalam adalah tumpukan lapisan seperti `torch.nn.Linear()` dan lainnya di atas satu sama lain).
* `A` adalah matriks bobot yang dibuat oleh lapisan, ini dimulai sebagai angka acak yang disesuaikan saat jaringan saraf belajar untuk merepresentasikan pola dalam data dengan lebih baik (perhatikan "`T`", itu karena matriks bobot dialihkan ).
  * **Catatan:** Anda mungkin juga sering melihat `W` atau huruf lain seperti `X` digunakan untuk menampilkan matriks bobot.
* `b` adalah istilah bias yang digunakan untuk sedikit mengimbangi bobot dan masukan.
* `y` adalah output (manipulasi input dengan harapan menemukan pola di dalamnya).

Ini adalah fungsi linier (Anda mungkin pernah melihat sesuatu seperti $y = mx+b$ di sekolah menengah atau di tempat lain), dan dapat digunakan untuk menggambar garis lurus!

Mari kita bermain-main dengan lapisan linier.

Coba ubah nilai `in_features` dan `out_features` di bawah dan lihat apa yang terjadi.

Apakah Anda memperhatikan ada hubungannya dengan bentuknya?

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


> **Question:** What happens if you change `in_features` from 2 to 3 above? Does it error? How could you change the shape of the input (`x`) to accomodate to the error? Hint: what did we have to do to `tensor_B` above?

Jika Anda belum pernah melakukannya, perkalian matriks bisa menjadi topik yang membingungkan pada awalnya.

Namun setelah Anda bermain-main dengannya beberapa kali dan bahkan membuka beberapa jaringan saraf, Anda akan melihatnya ada di mana-mana.

Ingat, hanya perkalian matriks yang Anda butuhkan.

![Anda hanya memerlukan perkalian matriks](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*Saat Anda mulai menggali lapisan jaringan saraf dan membangun lapisan Anda sendiri, Anda akan menemukan perkalian matriks di mana-mana. **Sumber:** https://marksaroufim.substack.com/p/working-class-deep-learner*

### Finding the min, max, mean, sum, etc (aggregation)

Sekarang kita telah melihat beberapa cara untuk memanipulasi tensor, mari kita lihat beberapa cara untuk menggabungkannya (mulai dari nilai yang lebih banyak ke nilai yang lebih kecil).

Pertama kita akan membuat tensor lalu mencari nilai maks, min, rata-rata, dan jumlahnya.





In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Sekarang mari kita lakukan beberapa agregasi.

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


> **Catatan:** Anda mungkin menemukan beberapa metode seperti `torch.mean()` mengharuskan tensor berada di `torch.float32` (yang paling umum) atau tipe data spesifik lainnya, jika tidak, operasi akan gagal.

Anda juga dapat melakukan hal yang sama seperti di atas dengan metode `torch`.

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Posisi min/maks

Anda juga dapat menemukan indeks tensor yang nilai maks atau minimumnya muncul dengan [`torch.argmax()`](https://pytorch.org/docs/stable/generated/torch.argmax.html) dan [`torch .argmin()`](https://pytorch.org/docs/stable/generated/torch.argmin.html) masing-masing.

Ini berguna jika Anda hanya menginginkan posisi dengan nilai tertinggi (atau terendah) dan bukan nilai sebenarnya (kita akan melihatnya di bagian selanjutnya saat menggunakan [fungsi aktivasi softmax](https://pytorch.org /docs/stable/generated/torch.nn.Softmax.html)).

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Ubah tipe data tensor

Seperti disebutkan, masalah umum dengan operasi pembelajaran mendalam adalah memiliki tensor dalam tipe data yang berbeda.

Jika satu tensor berada di `torch.float64` dan tensor lainnya berada di `torch.float32`, Anda mungkin mengalami beberapa error.

Tapi ada perbaikan.

Anda dapat mengubah tipe data tensor menggunakan [`torch.Tensor.type(dtype=None)`](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html) dengan `dtype` parameter adalah tipe data yang ingin Anda gunakan.

Pertama kita akan membuat tensor dan memeriksa tipe datanya (defaultnya adalah `torch.float32`).

In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

Sekarang kita akan membuat tensor lain yang sama seperti sebelumnya tetapi mengubah tipe datanya menjadi `torch.float16`.


In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

Dan kita bisa melakukan hal serupa untuk membuat tensor `torch.int8`.

In [ ]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

> **Catatan:** Tipe data yang berbeda pada awalnya bisa membingungkan. Namun bayangkan saja, semakin rendah angkanya (misalnya 32, 16, 8), semakin kurang presisi komputer menyimpan nilainya. Dan dengan jumlah penyimpanan yang lebih rendah, hal ini umumnya menghasilkan komputasi yang lebih cepat dan model keseluruhan yang lebih kecil. Jaringan saraf berbasis seluler sering kali beroperasi dengan bilangan bulat 8-bit, lebih kecil dan lebih cepat untuk dijalankan tetapi kurang akurat dibandingkan jaringan float32. Untuk informasi lebih lanjut tentang ini, saya telah membaca tentang [presisi dalam komputasi](https://en.wikipedia.org/wiki/Precision_(computer_science)).

> **Latihan:** Sejauh ini kita telah membahas beberapa metode tensor, tetapi masih banyak lagi di [dokumentasi `torch.Tensor`](https://pytorch.org/docs/stable/tensors.html) , saya sarankan menghabiskan 10 menit untuk menelusuri dan melihat apa pun yang menarik perhatian Anda. Klik pada mereka dan kemudian tuliskan sendiri dalam kode untuk melihat apa yang terjadi.

### Reshaping, stacking, squeezing and unsqueezing

Seringkali Anda ingin membentuk ulang atau mengubah dimensi tensor tanpa benar-benar mengubah nilai di dalamnya.

Untuk melakukannya, beberapa metode populer adalah:

| Metode | Deskripsi satu baris |
| ----- | ----- |
| [`torch.reshape(input, bentuk)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Membentuk ulang `input` menjadi `shape` (jika kompatibel), juga dapat menggunakan `torch.Tensor.reshape()`. |
| [`Tensor.view(bentuk)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Mengembalikan tampilan tensor asli dalam `bentuk` berbeda tetapi berbagi data yang sama dengan tensor asli. |
| [`torch.stack(tensor, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Menggabungkan urutan `tensor` sepanjang dimensi baru (`dim`), semua `tensor` harus berukuran sama. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Peras `input` untuk menghapus semua dimensi dengan nilai `1`. |
| [`torch.unsqueeze(input, redup)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Mengembalikan `input` dengan nilai dimensi `1` yang ditambahkan pada `dim`. |
| [`torch.permute(input, meredupkan)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Mengembalikan *tampilan* `input` asli dengan dimensinya yang diubah (diatur ulang) menjadi `dims`. |

Mengapa melakukan semua ini?

Karena model pembelajaran mendalam (jaringan saraf) adalah tentang memanipulasi tensor dengan cara tertentu. Dan karena aturan perkalian matriks, jika ada ketidakcocokan bentuk, Anda akan mengalami kesalahan. Metode ini membantu Anda memastikan elemen yang tepat dari tensor Anda tercampur dengan elemen yang tepat dari tensor lainnya.

Mari kita mencobanya.

Pertama, kita akan membuat tensor.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

Sekarang mari tambahkan dimensi ekstra dengan `torch.reshape()`.

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Kita juga bisa mengubah tampilan dengan `torch.view()`.

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Namun ingat, mengubah tampilan tensor dengan `torch.view()` sebenarnya hanya membuat tampilan baru dari tensor yang *sama*.

Jadi mengubah tampilan juga akan mengubah tensor aslinya.


In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

ika kita ingin menumpuk tensor baru di atasnya sebanyak lima kali, kita dapat melakukannya dengan `torch.stack()`.

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

Bagaimana kalau menghapus semua dimensi tunggal dari tensor?

Untuk melakukannya, Anda dapat menggunakan `torch.squeeze()` (Saya ingat ini sebagai *memeras* tensor agar hanya memiliki dimensi lebih dari 1).


In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


Dan untuk melakukan kebalikan dari `torch.squeeze()` Anda dapat menggunakan `torch.unsqueeze()` untuk menambahkan nilai dimensi 1 pada indeks tertentu.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


Anda juga dapat mengatur ulang urutan nilai sumbu dengan `torch.permute(input, dims)`, dengan `input` diubah menjadi *tampilan* dengan `dims` baru.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


> **Catatan**: Karena permutasi akan mengembalikan *tampilan* (berbagi data yang sama dengan aslinya), nilai dalam tensor yang diijinkan akan sama dengan tensor asli dan jika Anda mengubah nilai dalam tampilan, nilai tersebut akan berubah mengubah nilai aslinya.

## Indexing (selecting data from tensors)

Terkadang Anda ingin memilih data tertentu dari tensor (misalnya, hanya kolom pertama atau baris kedua).

Untuk melakukannya, Anda dapat menggunakan pengindeksan.

Jika Anda pernah melakukan pengindeksan pada daftar Python atau array NumPy, pengindeksan di PyTorch dengan tensor sangat mirip.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Nilai pengindeksan menjadi dimensi luar -> dimensi dalam (lihat tanda kurung siku).

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


Anda juga dapat menggunakan `:` untuk menentukan "semua nilai dalam dimensi ini" lalu menggunakan koma (`,`) untuk menambahkan dimensi lain.

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Pengindeksan bisa sangat membingungkan pada awalnya, terutama dengan tensor yang lebih besar (saya masih harus mencoba mengindeks beberapa kali untuk melakukannya dengan benar). Namun dengan sedikit latihan dan mengikuti moto penjelajah data (***visualisasikan, visualisasikan, visualisasi***), Anda akan mulai menguasainya.

## PyTorch tensors & NumPy

Karena NumPy adalah pustaka komputasi numerik Python yang populer, PyTorch memiliki fungsi untuk berinteraksi dengan baik.

Dua metode utama yang ingin Anda gunakan untuk NumPy ke PyTorch (dan kembali lagi) adalah:
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - Array NumPy -> tensor PyTorch.
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - Tensor PyTorch -> Array NumPy.

Mari kita mencobanya.

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

> **Catatan:** Secara default, array NumPy dibuat dengan tipe data `float64` dan jika Anda mengonversinya menjadi tensor PyTorch, tipe datanya akan tetap sama (seperti di atas).
>
> Namun, banyak penghitungan PyTorch yang defaultnya menggunakan `float32`.
>
> Jadi jika Anda ingin mengonversi array NumPy (float64) -> Tensor PyTorch (float64) -> Tensor PyTorch (float32), Anda dapat menggunakan `tensor = torch.from_numpy(array).type(torch.float32)`.

Karena kami menetapkan ulang `tensor` di atas, jika Anda mengubah tensor, arraynya akan tetap sama.


In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Dan jika Anda ingin beralih dari tensor PyTorch ke array NumPy, Anda dapat memanggil `tensor.numpy()`.

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

[teks link](https://)Dan aturan yang sama berlaku seperti di atas, jika Anda mengubah `tensor` asli, `numpy_tensor` baru tetap sama.

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

Saat Anda mempelajari lebih lanjut tentang jaringan saraf dan pembelajaran mesin, Anda akan mulai menemukan seberapa besar peran keacakan.

Ya, itu adalah keacakan semu. Karena bagaimanapun juga, ketika dirancang, sebuah komputer pada dasarnya bersifat deterministik (setiap langkah dapat diprediksi) sehingga keacakan yang dihasilkannya adalah keacakan yang disimulasikan (walaupun ada perdebatan mengenai hal ini juga, namun karena saya bukan seorang ilmuwan komputer, saya' Saya akan membiarkan Anda mengetahui lebih lanjut sendiri).

Lalu bagaimana hubungannya dengan jaringan saraf dan pembelajaran mendalam?

Kita telah membahas jaringan saraf yang dimulai dengan angka acak untuk mendeskripsikan pola dalam data (angka-angka ini adalah deskripsi yang buruk) dan mencoba meningkatkan angka acak tersebut menggunakan operasi tensor (dan beberapa hal lain yang belum kita bahas) untuk mendeskripsikan pola dengan lebih baik. data.

Pendeknya:

``mulai dengan angka acak -> operasi tensor -> coba menjadi lebih baik (lagi dan lagi dan lagi)``

Meskipun keacakan itu bagus dan kuat, terkadang Anda ingin mengurangi keacakan.

Mengapa?

Jadi, Anda dapat melakukan eksperimen berulang.

Misalnya, Anda membuat algoritme yang mampu mencapai performa X.

Dan kemudian teman Anda mencobanya untuk memverifikasi bahwa Anda tidak gila.

Bagaimana mereka bisa melakukan hal seperti itu?

Di sinilah **reprodusibilitas** berperan.

Dengan kata lain, bisakah Anda mendapatkan hasil yang sama (atau sangat mirip) di komputer Anda yang menjalankan kode yang sama seperti yang saya dapatkan di komputer saya?

Mari kita lihat contoh singkat reproduksibilitas di PyTorch.

Kita akan mulai dengan membuat dua tensor acak, karena keduanya acak, Anda pasti mengira keduanya berbeda, bukan?

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B:
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Seperti yang Anda duga, tensornya memiliki nilai yang berbeda.

Namun bagaimana jika Anda ingin membuat dua tensor acak dengan nilai *sama*.

Seperti halnya, tensor akan tetap berisi nilai acak tetapi rasanya sama.

Di situlah [`torch.manual_seed(seed)`](https://pytorch.org/docs/stable/generated/torch.manual_seed.html) berperan, dengan `seed` berupa bilangan bulat (seperti `42` tetapi bisa apa saja) yang menimbulkan keacakan.

Mari kita mencobanya dengan membuat lebih banyak tensor acak *berrasa*.

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Bagus!

Sepertinya pengaturan benih berhasil.

> **Sumber Daya:** Apa yang baru saja kita bahas hanya membahas permukaan reproduktifitas di PyTorch. Untuk informasi lebih lanjut, tentang reproduksibilitas secara umum dan benih acak, saya akan memeriksa:
> * [Dokumentasi reproduksibilitas PyTorch](https://pytorch.org/docs/stable/notes/randomness.html) (latihan yang baik adalah membaca ini selama 10 menit dan bahkan jika Anda tidak memahaminya sekarang, menyadari hal itu adalah penting).
> * [Halaman benih acak Wikipedia](https://en.wikipedia.org/wiki/Random_seed) (ini akan memberikan gambaran umum yang bagus tentang benih acak dan keacakan semu secara umum).

## Running tensors on GPUs (and making faster computations)

Algoritme pembelajaran mendalam memerlukan banyak operasi numerik.

Dan secara default operasi ini sering dilakukan pada CPU (unit pengolah komputer).

Namun, ada perangkat keras umum lainnya yang disebut GPU (unit pemrosesan grafis), yang seringkali jauh lebih cepat dalam melakukan jenis operasi tertentu yang dibutuhkan jaringan saraf (perkalian matriks) dibandingkan CPU.

Komputer Anda mungkin memilikinya.

Jika demikian, Anda harus menggunakannya kapan pun Anda bisa untuk melatih jaringan saraf karena kemungkinan besar ini akan mempercepat waktu pelatihan secara dramatis.

Ada beberapa cara untuk pertama mendapatkan akses ke GPU dan kedua membuat PyTorch menggunakan GPU tersebut.

> **Catatan:** Saat saya merujuk "GPU" sepanjang kursus ini, saya merujuk pada [GPU Nvidia dengan CUDA](https://developer.nvidia.com/cuda-gpus) yang diaktifkan (CUDA adalah platform komputasi dan API yang membantu memungkinkan GPU digunakan untuk komputasi tujuan umum & bukan hanya grafis) kecuali ditentukan lain.




### 1. Getting a GPU

Anda mungkin sudah tahu apa yang terjadi ketika saya mengatakan GPU. Namun jika tidak, ada beberapa cara untuk mengaksesnya.

| **Metode** | **Kesulitan dalam penyiapan** | **Kelebihan** | **Kontra** | **Cara pengaturan** |
| ----- | ----- | ----- | ----- | ----- |
| Google Kolab | Mudah | Gratis untuk digunakan, hampir tidak diperlukan pengaturan, dapat berbagi pekerjaan dengan orang lain semudah tautan | Tidak menyimpan keluaran data Anda, komputasi terbatas, tunduk pada batas waktu | [Ikuti Panduan Google Colab](https://colab.research.google.com/notebooks/gpu.ipynb) |
| Gunakan | Sedang | Jalankan semuanya secara lokal di mesin Anda sendiri | GPU tidak gratis, memerlukan biaya di muka | Ikuti [panduan instalasi PyTorch](https://pytorch.org/get-started/locally/) |
| Komputasi awan (AWS, GCP, Azure) | Sedang-Keras | Biaya awal yang kecil, akses ke komputasi yang hampir tak terbatas | Bisa mahal jika dijalankan terus-menerus, memerlukan waktu untuk menyiapkannya kan | Ikuti [panduan instalasi PyTorch](https://pytorch.org/get-started/cloud-partners/) |

Ada lebih banyak pilihan untuk menggunakan GPU tetapi tiga di atas sudah cukup untuk saat ini.

Secara pribadi, saya menggunakan kombinasi Google Colab dan komputer pribadi saya untuk eksperimen skala kecil (dan membuat kursus ini) dan menggunakan sumber daya cloud saat saya membutuhkan lebih banyak daya komputasi.

> **Referensi:** Jika Anda ingin membeli GPU sendiri tetapi tidak yakin apa yang harus dibeli, [Tim Dettmers memiliki panduan yang bagus](https://timdettmers.com/2020/09/07/which -gpu-untuk-pembelajaran mendalam/).

Untuk memeriksa apakah Anda memiliki akses ke GPU Nvidia, Anda dapat menjalankan `!nvidia-smi` dengan tanda `!` (juga disebut bang) berarti "jalankan ini di baris perintah".



In [ ]:
!nvidia-smi

Thu Jan  4 07:38:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

Jika Anda tidak memiliki GPU Nvidia yang dapat diakses, tampilan di atas akan menghasilkan sesuatu seperti:

```
NVIDIA-SMI gagal karena tidak dapat berkomunikasi dengan driver NVIDIA. Pastikan driver NVIDIA terbaru telah diinstal dan dijalankan.
```

Jika demikian, kembali ke atas dan ikuti langkah-langkah penginstalan.

Jika Anda memiliki GPU, baris di atas akan menampilkan sesuatu seperti:

```
Rabu 19 Januari 22:09:08 2022
+------------------------------------------------- ----------------------------+
| NVIDIA-SMI 495.46 Versi Driver: 460.32.03 Versi CUDA: 11.2 |
|----------------+----------------- -----+-------+
| Persistensi Nama GPU-M| Bus-Id Disp.A | Uncorr yang Volatil. ECC |
| Performa Temperatur Kipas: Penggunaan/Batas| Penggunaan Memori | GPU-Util Hitung M. |
| | | MIG M.|
|================+== =====+=======|
| 0 Tesla P100-PCIE... Mati | 00000000:00:04.0 Diskon | 0 |
| Tidak Ada 35C P0 27W / 250W | 0MiB / 16280MiB | 0% Bawaan |
| | | T/A |
+----------------+----------------- -----+-------+
                                                                               
+------------------------------------------------- ----------------------------+
| Proses: |
| GPU GI CI Tipe PID Nama proses Memori GPU |
| ID Penggunaan ID |
| ===== =============|
| Tidak ditemukan proses yang berjalan |
+------------------------------------------------- ----------------------------+
```



### 2. Getting PyTorch to run on the GPU

Once you've got a GPU ready to access, the next step is getting PyTorch to use for storing data (tensors) and computing on data (performing operations on tensors).

To do so, you can use the [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html) package.

Rather than talk about it, let's try it out.

You can test if PyTorch has access to a GPU using [`torch.cuda.is_available()`](https://pytorch.org/docs/stable/generated/torch.cuda.is_available.html#torch.cuda.is_available).


In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

Jika keluaran di atas `True`, PyTorch dapat melihat dan menggunakan GPU, jika keluarannya `False`, PyTorch tidak dapat melihat GPU dan dalam hal ini, Anda harus kembali melalui langkah-langkah instalasi.

Sekarang, katakanlah Anda ingin mengatur kode Anda agar berjalan pada CPU *atau* GPU jika tersedia.

Dengan begitu, jika Anda atau seseorang memutuskan untuk menjalankan kode Anda, kode tersebut akan berfungsi terlepas dari perangkat komputasi yang mereka gunakan.

Mari buat variabel `perangkat` untuk menyimpan jenis perangkat yang tersedia.

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Jika keluaran di atas `"cuda"` berarti kita dapat mengatur semua kode PyTorch kita untuk menggunakan perangkat CUDA yang tersedia (GPU) dan jika mengeluarkan `"cpu"`, kode PyTorch kita akan menempel pada CPU.

> **Catatan:** Di PyTorch, praktik terbaiknya adalah menulis [**kode agnostik perangkat**](https://pytorch.org/docs/master/notes/cuda.html#device-agnostic-code). Ini berarti kode yang akan dijalankan pada CPU (selalu tersedia) atau GPU (jika tersedia).

Jika Anda ingin melakukan komputasi lebih cepat, Anda dapat menggunakan GPU tetapi jika Anda ingin melakukan komputasi *jauh* lebih cepat, Anda dapat menggunakan beberapa GPU.

Anda dapat menghitung jumlah GPU yang dapat diakses oleh PyTorch menggunakan [`torch.cuda.device_count()`](https://pytorch.org/docs/stable/generated/torch.cuda.device_count.html#torch.cuda. jumlah_perangkat).


In [ ]:
# Count number of devices
torch.cuda.device_count()

1

Mengetahui jumlah GPU yang dapat diakses oleh PyTorch sangat membantu jika Anda ingin menjalankan proses tertentu pada satu GPU dan proses lain pada GPU lainnya (PyTorch juga memiliki fitur yang memungkinkan Anda menjalankan proses di *semua* GPU).

### 3. Putting tensors (and models) on the GPU

Anda dapat menempatkan tensor (dan model, kita akan melihatnya nanti) pada perangkat tertentu dengan memanggil [`to(device)`](https://pytorch.org/docs/stable/generated/torch.Tensor.to. html) pada mereka. Dimana `device` adalah perangkat target yang ingin dituju tensor (atau modelnya).

Kenapa melakukan ini?

GPU menawarkan komputasi numerik yang jauh lebih cepat daripada CPU dan jika GPU tidak tersedia, karena **kode agnostik perangkat** kami (lihat di atas), GPU akan berjalan di CPU.

> **Catatan:** Menempatkan tensor pada GPU menggunakan `to(device)` (mis. `some_tensor.to(device)`) akan mengembalikan salinan tensor tersebut, mis. tensor yang sama akan ada di CPU dan GPU. Untuk menimpa tensor, tetapkan ulang tensor:
>
> `some_tensor = some_tensor.to(perangkat)`

Mari kita coba membuat tensor dan meletakkannya di GPU (jika tersedia).

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Jika Anda memiliki GPU yang tersedia, kode di atas akan menampilkan sesuatu seperti:

```
tensor([1, 2, 3]) cpu
tensor([1, 2, 3], perangkat='cuda:0')
```

Perhatikan tensor kedua memiliki `device='cuda:0'`, artinya disimpan pada GPU ke-0 yang tersedia (GPU diindeks 0, jika ada dua GPU yang tersedia, maka akan menjadi `'cuda:0'` dan `' cuda:1'` masing-masing, hingga `'cuda:n'`).

### 4. Moving tensors back to the CPU

Bagaimana jika kita ingin memindahkan tensor kembali ke CPU?

Misalnya, Anda ingin melakukan ini jika ingin berinteraksi dengan tensor Anda dengan NumPy (NumPy tidak memanfaatkan GPU).

Mari kita coba menggunakan metode [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) pada `tensor_on_gpu` kita.

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

Sebagai gantinya, untuk mengembalikan tensor ke CPU dan dapat digunakan dengan NumPy, kita dapat menggunakan [`Tensor.cpu()`](https://pytorch.org/docs/stable/generated/torch.Tensor.cpu.html).

Ini menyalin tensor ke memori CPU sehingga dapat digunakan dengan CPU.

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Cara di atas mengembalikan salinan tensor GPU di memori CPU sehingga tensor asli masih di GPU.

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')